courses=['History','Math','Physics','Computer']
print(courses)
print("\n Reversing courses :")
courses.reverse()
print(courses)
print("\n Sorting the courses :")
courses.sort()
print(courses)
print("\n Sorting the numbers:")
nums=[1,25,4,8,40,9,34,22]
nums.sort()
print(nums)
print("\n")
print("The courses and numbers in descending order are:")
courses.sort(reverse=True)
nums.sort(reverse=True)
print(courses)
print(nums)
print("\n Another and used method for sorting :")
sorted_courses=sorted(courses)
sorted_nums=sorted(nums)
print(sorted_courses)
print(sorted_nums)